language: php
php:
- 5.6
- 7.0
- hhvm
os:
- linux
branches:
  only:
  - master
  - dev
  
before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  
install:
  - composer install
script:
  - vendor/bin/phpunit