language: php
os: linux
dist: xenial
php:
  - 7.1
  - 7.2
git:
  depth: 99999
branches:
  except:
  - gh-pages
env:
  global:
   - secure: EiBlxeIgN532PBTn0+XVOB3FN0XFBV2EwrnA+yOYl/NNrmgAKlrUscIEuHFVC2aHhPw4NEIwob2kCNnMN9J605RxM5kpXmTqnC6IMYsBmlYX3kETAxOetbpS6ndrIH0AS1r7nG3scGhqKCn2xTsgsTF06QvRFM6Q/ZZFTPQkKTw=
   - secure: 11SCrzAe/rLYhtIr1dGe4rHAayU9gbz1WYTClsvzNZYsswramumJWtbtK1z0LEWBhU5Ii8FutzMN8sUOf2IFH2gZMsx3TY2DRn2WnNdiBOAS5pDIN/ms+zB82bFjsESnRp4gLT6g92+e6nMTkWM84cwtZfV1mTSQ2ZYwrXdE/NA=
install:
- composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
- composer self-update
- composer update
- composer install --no-interaction
script:
- php vendor/bin/phpunit
after_success:
- php codacycoverage phpunit
