language: php
php:
  - 5.6
  - 7.0
  - hhvm
os:
  - linux
branches:
  only:
    - master
    - dev
before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
install:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer self-update
  - composer install --no-interaction
script:
  - php vendor/bin/phpunit
after_success:
  - php codacycoverage phpunit
env:
  global:
    - secure: i0JLw/7Ih81SljZXLkkFP6KPhLZT9SiCAdWloKcRpPCsTxwGJqXKuIbZ85YRmqsCpfpop3cPQYfUwT9HL9vcAc37puG1kyKXc3kYlv6ju5/kIsAn9SoN3eOKnBHpaGc6Hz9G7gGPB/yKyanYzDC/bjP7RzOZr9TGf4d0Y8yRbg8=
    - secure: 11SCrzAe/rLYhtIr1dGe4rHAayU9gbz1WYTClsvzNZYsswramumJWtbtK1z0LEWBhU5Ii8FutzMN8sUOf2IFH2gZMsx3TY2DRn2WnNdiBOAS5pDIN/ms+zB82bFjsESnRp4gLT6g92+e6nMTkWM84cwtZfV1mTSQ2ZYwrXdE/NA=
