language: php
php:
- 5.6
- 7.0
- hhvm
os:
- linux
branches:
  only:
  - master
  - dev
  
before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
install:
  - composer self-update
  - composer install
script:
  - php vendor/bin/phpunit
after_success:
  - php codacycoverage
  
env:
  global:
    secure: i0JLw/7Ih81SljZXLkkFP6KPhLZT9SiCAdWloKcRpPCsTxwGJqXKuIbZ85YRmqsCpfpop3cPQYfUwT9HL9vcAc37puG1kyKXc3kYlv6ju5/kIsAn9SoN3eOKnBHpaGc6Hz9G7gGPB/yKyanYzDC/bjP7RzOZr9TGf4d0Y8yRbg8=